name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Generate Pacman graph
        run: |
          rm -rf pacman-output
          mkdir -p pacman-output
          
          # Usando o script local em vez de baixar da internet
          python scripts/pacman.py --username ${{ github.repository_owner }} --output pacman-output/pacman-contribution-graph.svg
          
          # Gera versão dark
          python scripts/pacman.py --username ${{ github.repository_owner }} --output pacman-output/pacman-contribution-graph-dark.svg --dark

      - name: Deploy to pacman-output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pacman-output
          publish_dir: ./pacman-output
          force_orphan: true
